name: Build, lint and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint, build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install playwright
        run: bunx playwright install chromium-headless-shell --with-deps

      - name: Build, lint and test
        run: bun run build && bun run lint && bun run test

      - name: Deploy to Azure
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        if: github.ref == 'refs/heads/master'
        with:
          source-path: dist
          sas-url: ${{ secrets.DEPLOY_SAS_URL }}
          require-index: false
