name: Build, lint and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint, build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true

      - name: Build
        run: npm run build

      - name: Deploy to Azure
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        if: github.ref == 'refs/heads/master'
        with:
          source-path: dist
          sas-url: ${{ secrets.DEPLOY_SAS_URL }}
          require-index: false
